/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DTO.DotGiamGiaDTO;
import DTO.GioHangDTO;
import DTO.KhachHangDTO;
import DTO.PhieuGiaoHangDTO;
import DTO.PhieuGiaoHangDTO1;
import DTO.SanPhamDTO;
import Model.PhieuGiaoChiTiet;
import Model.PhieuGiaoHang;
import Service.PhieuGiaoHang_SV;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class GiaoHangJPanel extends javax.swing.JPanel {

    private int makh;
    private int mapg;
    private int mapg1;

    private int makhcl;
    private int madscl;

    DefaultTableModel tblModel;
    List<PhieuGiaoHang> ldsv = new ArrayList<>();
    List<SanPhamDTO> listSP = new ArrayList<>();
    PhieuGiaoHang pgh;
    PhieuGiaoHang_SV sv = new PhieuGiaoHang_SV();
    List<DotGiamGiaDTO> listdto = sv.getAllcboPhieuGiam();
    List<GioHangDTO> GioDTO = new ArrayList<>();
    List<KhachHangDTO> khDTO = new ArrayList<>();
    List<PhieuGiaoHangDTO> pghDTO = new ArrayList<>();
    List<PhieuGiaoHangDTO1> pghDTO1 = new ArrayList<>();
    List<PhieuGiaoChiTiet> pgct = new ArrayList<>();
    PhieuGiaoChiTiet pgct1;

    public GiaoHangJPanel() {
        initComponents();
        initCBOKhuyenMai();
        ldsv = sv.getAllPhieuGiaoHang();
        fillTable(ldsv);
        listSP = sv.getAllSanPham();
        fillTableSP(listSP);
        khDTO = sv.getAllKhachHang();
        fillTableKhachHang(khDTO);
        pghDTO1 = sv.getAllTaoDSPG();
        fillTableTaoDSPG(pghDTO1);
        listdto = sv.getAllcboPhieuGiam();

        pgct = sv.selectAllPhieuChiTiet();
        fillSanPhamDSPG(pgct);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel26 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtDiaChiGiao = new javax.swing.JTextArea();
        txtMaPhieuGiao1 = new javax.swing.JLabel();
        txtGiaoHoanThanh = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        txtXacNhanKhachHang = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtNVNhanDon = new javax.swing.JLabel();
        txtNhanVienGiaoHang = new javax.swing.JLabel();
        txtTimeDuKien = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        txtPhiVanChuyen1 = new javax.swing.JLabel();
        txtTienKhachDuaDSPG = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        cboTK = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPhieuGiaoHang1 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblSanPhamDSPG = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDanhsachsp = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        cboMaKhuyenMai = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtMucGiam = new javax.swing.JTextField();
        txtNhanTienKhach = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        btnTaoPhieu = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        txtTongTien15 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txtTongTien16 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jSeparator29 = new javax.swing.JSeparator();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtDiaChiTaoPhieu = new javax.swing.JTextField();
        txtPhiVanChuyen = new javax.swing.JTextField();
        btnGiaoHanhg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChiTaoHoaDon = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        txtSoDT = new javax.swing.JTextField();
        txtNguoiNhan = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txtTimKiemKhachHang = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblTaoDSPG = new javax.swing.JTable();

        jTabbedPane6.setBackground(new java.awt.Color(255, 204, 102));
        jTabbedPane6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane6.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTabbedPane6.setFont(new java.awt.Font("Serif", 1, 13)); // NOI18N
        jTabbedPane6.setPreferredSize(new java.awt.Dimension(1101, 632));

        jPanel26.setBackground(new java.awt.Color(255, 204, 102));

        jLabel78.setText("Mã Phiếu Giao :");

        jLabel79.setText("Nhân Viên Tạo Đơn :");

        jLabel80.setText("Tổng Tiền :");

        jLabel81.setText("Tên Khách Hàng :");

        jLabel82.setText("Mã Sản Phẩm :");

        jLabel83.setText("Số Lượng :");

        jLabel84.setText("Địa Chỉ Giao :");

        txtDiaChiGiao.setColumns(20);
        txtDiaChiGiao.setRows(5);
        jScrollPane10.setViewportView(txtDiaChiGiao);

        txtMaPhieuGiao1.setText("---------------------------------------");

        txtGiaoHoanThanh.setText("---------------------------------------");

        txtTenKH.setText("---------------------------------------");

        txtMaSP.setText("---------------------------------------");

        txtTongTien.setText("---------------------------------------");

        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 5, true));

        jLabel86.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(0, 153, 153));
        jLabel86.setText("Khách Hàng Xác Nhận :");

        txtXacNhanKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtXacNhanKhachHang.setForeground(new java.awt.Color(255, 0, 0));
        txtXacNhanKhachHang.setText("Chưa Nhận Hàng");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel86)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(txtXacNhanKhachHang)
                .addGap(34, 34, 34))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtXacNhanKhachHang))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel86)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel48.setText("Nhân Viên Giao Hàng :");

        jLabel50.setText("Giao Dự Kiến :");

        txtNVNhanDon.setText("---------------------------------------");

        txtNhanVienGiaoHang.setText("---------------------------------------");

        txtTimeDuKien.setText("---------------------------------------");

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang Chuẩn Bị", "Đã Giao Hàng", "Đang Vận Chuyển ", "Thất Lạc Hàng", "Đang Tạo" }));
        cboTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTrangThaiActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 0, 0));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/updated.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red));
        btnCapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCapNhat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 0, 0));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/remove.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red));
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel89.setText("Trạng Thái Đơn Hàng  :");

        jLabel90.setText("Giao Hoàn Thành :");

        txtSoLuong.setText("---------------------------------------");

        jLabel85.setText("Ghi Chú :");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane11.setViewportView(txtGhiChu);

        jLabel91.setText("Phí Vận Chuyển :");

        jLabel92.setText("Tiền Khách Đưa :");

        txtPhiVanChuyen1.setText("---------------------------------------");

        txtTienKhachDuaDSPG.setText("---------------------------------------");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel78)
                            .addComponent(jLabel79)
                            .addComponent(jLabel48)
                            .addComponent(jLabel50)
                            .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaPhieuGiao1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNVNhanDon, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNhanVienGiaoHang, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTimeDuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaoHoanThanh, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel25Layout.createSequentialGroup()
                                .addComponent(jLabel84)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel25Layout.createSequentialGroup()
                                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPhiVanChuyen1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTienKhachDuaDSPG, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel25Layout.createSequentialGroup()
                                .addComponent(jLabel81)
                                .addGap(37, 37, 37)
                                .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel25Layout.createSequentialGroup()
                                .addComponent(jLabel82)
                                .addGap(49, 49, 49)
                                .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel25Layout.createSequentialGroup()
                                .addComponent(jLabel83)
                                .addGap(71, 71, 71)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel25Layout.createSequentialGroup()
                                .addComponent(jLabel89)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel25Layout.createSequentialGroup()
                                .addComponent(jLabel85)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel25Layout.createSequentialGroup()
                                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel25Layout.createSequentialGroup()
                                        .addComponent(jLabel78)
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel79)
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel48)
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel50)
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel90))
                                    .addGroup(jPanel25Layout.createSequentialGroup()
                                        .addComponent(txtMaPhieuGiao1)
                                        .addGap(15, 15, 15)
                                        .addComponent(txtNVNhanDon)
                                        .addGap(15, 15, 15)
                                        .addComponent(txtNhanVienGiaoHang)
                                        .addGap(15, 15, 15)
                                        .addComponent(txtTimeDuKien)
                                        .addGap(15, 15, 15)
                                        .addComponent(txtGiaoHoanThanh)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPhiVanChuyen1)
                                    .addComponent(jLabel91))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel92)
                                    .addComponent(txtTienKhachDuaDSPG))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel84)))
                            .addGroup(jPanel25Layout.createSequentialGroup()
                                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel81)
                                    .addComponent(txtTenKH))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel82)
                                    .addComponent(txtMaSP))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel83)
                                    .addComponent(txtSoLuong))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel89))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTongTien)
                                    .addComponent(jLabel80))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel85)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_28px.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel41.setText("Tìm Kiếm :");

        cboTK.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        cboTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hôm Nay", "1 Tuần", "1 Tháng ", "1 Năm" }));
        cboTK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cboTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTKActionPerformed(evt);
            }
        });

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Phiếu Giao Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Source Sans Pro Black", 0, 15), new java.awt.Color(255, 0, 0))); // NOI18N
        jScrollPane4.setForeground(new java.awt.Color(255, 0, 0));

        tblPhieuGiaoHang1.setForeground(new java.awt.Color(255, 0, 0));
        tblPhieuGiaoHang1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã PG", "NV Tạo Đơn", "Tên KH", "Ngày Giao DK", "Trạng Thái"
            }
        ));
        tblPhieuGiaoHang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuGiaoHang1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPhieuGiaoHang1);

        jScrollPane8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dịch Vụ Được Giao", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Source Sans Pro Black", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        tblSanPhamDSPG.setForeground(new java.awt.Color(255, 0, 0));
        tblSanPhamDSPG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Phiếu Giao", "Mã Sản Phẩm", "Số Lượng", "Mã Khách Hàng", ""
            }
        ));
        tblSanPhamDSPG.setSelectionForeground(new java.awt.Color(255, 0, 0));
        tblSanPhamDSPG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamDSPGMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblSanPhamDSPG);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel26Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane8)))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel41)
                        .addComponent(cboTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane6.addTab("Danh sách phiếu giao hàng", jPanel26);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(967, 600));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Source Sans Pro Black", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        tblDanhsachsp.setForeground(new java.awt.Color(255, 0, 0));
        tblDanhsachsp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Tên Loại", "Size", "Trạng Thái", "Giá ", "Mô Tả", ""
            }
        ));
        tblDanhsachsp.setSelectionForeground(new java.awt.Color(255, 0, 0));
        tblDanhsachsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhsachspMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblDanhsachspMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(tblDanhsachsp);

        jScrollPane5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dịch Vụ Được Giao", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Source Sans Pro Black", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        tblGioHang.setForeground(new java.awt.Color(255, 0, 0));
        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm ", "Tên Loại", "Size", "Trạng Thái", "Giá", "Mô Tả", "Số Lượng", ""
            }
        ));
        tblGioHang.setSelectionForeground(new java.awt.Color(255, 0, 0));
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblGioHang);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 0, 0));
        jLabel40.setText("Tổng Tiền : ");

        cboMaKhuyenMai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMaKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboMaKhuyenMaiMouseClicked(evt);
            }
        });
        cboMaKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaKhuyenMaiActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 0, 0));
        jLabel42.setText("Mức Giảm :");

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 0, 0));
        jLabel43.setText("Tiền Khách Đưa :");

        txtMucGiam.setEnabled(false);
        txtMucGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMucGiamActionPerformed(evt);
            }
        });

        btnTaoPhieu.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        btnTaoPhieu.setForeground(new java.awt.Color(255, 0, 0));
        btnTaoPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cash_register_56px.png"))); // NOI18N
        btnTaoPhieu.setText("Tạo Phiếu Giao");
        btnTaoPhieu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTaoPhieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTaoPhieuMouseClicked(evt);
            }
        });
        btnTaoPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoPhieuActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 0, 0));
        jLabel44.setText("Tiền Thừa :");

        txtTongTien15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTongTien15.setForeground(new java.awt.Color(102, 102, 102));
        txtTongTien15.setText("0");

        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(102, 102, 102));
        jLabel54.setText("VND");

        txtTongTien16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTongTien16.setForeground(new java.awt.Color(102, 102, 102));
        txtTongTien16.setText("0");

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(102, 102, 102));
        jLabel55.setText("VND");

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 0, 0));
        jLabel56.setText("Tên KH :");

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 0, 0));
        jLabel57.setText("Mã Khuyến Mãi :");

        jLabel58.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 0, 0));
        jLabel58.setText("Số DT :");

        jLabel60.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 0, 0));
        jLabel60.setText("Phí Vận Chuyển :");

        jLabel59.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 0, 0));
        jLabel59.setText("Địa Chỉ :");

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 0, 0));
        jLabel45.setText("Ghi Chú :");

        txtDiaChiTaoPhieu.setFont(new java.awt.Font("Serif", 0, 13)); // NOI18N
        txtDiaChiTaoPhieu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiaChiTaoPhieu.setDisabledTextColor(new java.awt.Color(0, 153, 153));

        btnGiaoHanhg.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        btnGiaoHanhg.setForeground(new java.awt.Color(255, 0, 0));
        btnGiaoHanhg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cash_register_56px.png"))); // NOI18N
        btnGiaoHanhg.setText("Giao Hàng");
        btnGiaoHanhg.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGiaoHanhg.setIconTextGap(30);
        btnGiaoHanhg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaoHanhgActionPerformed(evt);
            }
        });

        txtGhiChiTaoHoaDon.setColumns(20);
        txtGhiChiTaoHoaDon.setRows(5);
        jScrollPane1.setViewportView(txtGhiChiTaoHoaDon);

        txtSoDT.setFont(new java.awt.Font("Serif", 0, 13)); // NOI18N
        txtSoDT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSoDT.setDisabledTextColor(new java.awt.Color(0, 153, 153));

        txtNguoiNhan.setFont(new java.awt.Font("Serif", 0, 13)); // NOI18N
        txtNguoiNhan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNguoiNhan.setDisabledTextColor(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGiaoHanhg, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTaoPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNhanTienKhach)))
                .addContainerGap())
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jSeparator29, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addComponent(jSeparator26, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addComponent(jSeparator3))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel57)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboMaKhuyenMai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDiaChiTaoPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel44)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTongTien15))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel40)
                                        .addGap(57, 57, 57)
                                        .addComponent(txtTongTien16)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel55)
                                    .addComponent(jLabel54))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel56)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNguoiNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel60)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhiVanChuyen)
                        .addContainerGap())
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(37, 37, 37)
                        .addComponent(txtMucGiam))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(txtNguoiNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChiTaoPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(cboMaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtMucGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(txtNhanTienKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(txtPhiVanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtTongTien16)
                    .addComponent(jLabel55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTien15)
                    .addComponent(jLabel54)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTaoPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGiaoHanhg, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 204, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Source Sans Pro Black", 0, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel9.setForeground(new java.awt.Color(255, 0, 0));
        jPanel9.setFont(new java.awt.Font("Source Sans Pro Black", 0, 14)); // NOI18N

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "Địa Chỉ", "Số ĐT"
            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseEntered(evt);
            }
        });
        jScrollPane6.setViewportView(tblKhachHang);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Tìm Kiếm :");

        txtTimKiemKhachHang.setToolTipText("Vui Lòng Nhập Tên Khách Hàng");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/search_28px.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/note.png"))); // NOI18N
        jButton2.setText("Sửa Thông Tin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimKiemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Phiếu Giao Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Source Sans Pro Black", 0, 15), new java.awt.Color(255, 0, 0))); // NOI18N
        jScrollPane7.setForeground(new java.awt.Color(255, 0, 0));

        tblTaoDSPG.setForeground(new java.awt.Color(255, 0, 0));
        tblTaoDSPG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Phiếu Giao", "Tên Khách Hàng", "NV Tạo Đơn", "Trạng Thái"
            }
        ));
        tblTaoDSPG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaoDSPGMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblTaoDSPG);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7))
                .addGap(49, 49, 49)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane6.addTab("Tạo phiếu giao hàng", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1101, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTrangThaiActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        sv.UpdatePhieuGiaoHang(String.valueOf(cboTrangThai.getSelectedItem()), Integer.parseInt(txtMaPhieuGiao1.getText()));
        ldsv = sv.getAllPhieuGiaoHang();
        fillTable(ldsv);
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        sv.DeletePhieuGiaoHang(Integer.parseInt(txtMaPhieuGiao1.getText()), Integer.parseInt(txtMaPhieuGiao1.getText()));
        JOptionPane.showMessageDialog(this, "Xóa Phiếu Thành Công");
        ldsv = sv.getAllPhieuGiaoHang();
        fillTable(ldsv);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //        ldsv = null;
        //        ldsv = sv.getAllPhieuGiaoHangID(Integer.parseInt(txtTimKiem.getText()));
        //
        //        fillTable(ldsv);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cboTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTKActionPerformed

    }//GEN-LAST:event_cboTKActionPerformed

    private void tblPhieuGiaoHang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuGiaoHang1MouseClicked
        // TODO add your handling code here:
        //        int point = tblPhieuGiaoHang1.getSelectedRow();
        //        setModelpgh(ldsv.get(point));
        //        pgct = sv.selectAllPhieuChiTiet();
        //        fillSanPhamDSPG(pgct);
        int selectedRow = tblPhieuGiaoHang1.getSelectedRow();

        if (selectedRow != -1) {
            // Retrieve the value from column 1
            Object valueAtColumn1Object = tblPhieuGiaoHang1.getValueAt(selectedRow, 0);

            // Check if the value is not null and is of type Integer
            if (valueAtColumn1Object != null && valueAtColumn1Object instanceof Integer) {
                int valueAtColumn1 = (int) valueAtColumn1Object;

                // Now you can use 'valueAtColumn1' as needed
                System.out.println("Value at column 1: " + valueAtColumn1);

                // Your existing code...
                setModelpgh(ldsv.get(selectedRow));
                pgct = sv.getAllPhieuChiTiet(valueAtColumn1);
                fillSanPhamDSPG(pgct);
            } else {
                System.out.println("Value at column 1 is not an Integer or is null.");
            }
        }
    }//GEN-LAST:event_tblPhieuGiaoHang1MouseClicked

    private void tblSanPhamDSPGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamDSPGMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSanPhamDSPGMouseClicked

    private void tblDanhsachspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhsachspMouseClicked
        // TODO add your handling code here:
        int point = tblDanhsachsp.getSelectedRow();

        SanPhamDTO selectedSP = listSP.get(point);

        // Check if the item is already in the cart
        boolean found = false;
        for (GioHangDTO gioHangDTO : GioDTO) {
            if (gioHangDTO.getMaSanPham() == selectedSP.getMaSanPham()) {
                gioHangDTO.setSoLuong(gioHangDTO.getSoLuong() + 1);
                found = true;
                break;
            }
        }

        // If the item is not in the cart, add a new entry
        if (!found) {
            GioHangDTO gioHangDTO = new GioHangDTO();
            gioHangDTO.setMaSanPham(selectedSP.getMaSanPham());
            gioHangDTO.setTenSanPham(selectedSP.getTenSanPham());
            gioHangDTO.setTenLoai(selectedSP.getTenLoai());
            gioHangDTO.setSize(selectedSP.getSize());
            gioHangDTO.setTrangThai(selectedSP.getTrangThai());
            gioHangDTO.setGia(selectedSP.getGia());
            gioHangDTO.setMoTa(selectedSP.getMoTa());
            gioHangDTO.setSoLuong(1);
            GioDTO.add(gioHangDTO);
        }

        // Update the cart display
        fillGioHang(GioDTO);

    }//GEN-LAST:event_tblDanhsachspMouseClicked

    private void tblDanhsachspMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhsachspMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDanhsachspMouseEntered

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioHangMouseClicked
        // TODO add your handling code here:
        int point = tblGioHang.getSelectedRow();
        int tb = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa sản phẩm này không ?", "Xác nhận", JOptionPane.OK_CANCEL_OPTION);
        if (tb == JOptionPane.OK_OPTION) {
            GioHangDTO selectedGH = GioDTO.get(point);

            // Use iterator to safely remove the item while iterating
            Iterator<GioHangDTO> iterator = GioDTO.iterator();
            while (iterator.hasNext()) {
                GioHangDTO gioHangDTO = iterator.next();
                if (gioHangDTO.getMaSanPham() == selectedGH.getMaSanPham()) {
                    iterator.remove(); // Remove the current item from the list
                }
            }

            // Update the cart display after removal
            fillGioHang(GioDTO);
        }
    }//GEN-LAST:event_tblGioHangMouseClicked

    private void cboMaKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMaKhuyenMaiMouseClicked
        // TODO add your handling code here:
        //                checkMucGiamGia(cboMaKhuyenMai.getSelectedItem()+"");
    }//GEN-LAST:event_cboMaKhuyenMaiMouseClicked

    private void cboMaKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaKhuyenMaiActionPerformed
        // TODO add your handling code here:
        checkMucGiamGia(cboMaKhuyenMai.getSelectedItem() + "");
    }//GEN-LAST:event_cboMaKhuyenMaiActionPerformed

    private void txtMucGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMucGiamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMucGiamActionPerformed

    private void btnTaoPhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoPhieuMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnTaoPhieuMouseClicked

    private void btnTaoPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoPhieuActionPerformed
        // TODO add your handling code here:
        //    private int makhcl;
        //    private int madscl;
        sv.insertTaoPhieuGiao(getModelTaopgh());
        pghDTO1 = sv.getAllTaoDSPG();
        fillTableTaoDSPG(pghDTO1);
        JOptionPane.showMessageDialog(this, "Tạo Phiếu Thành Công");
        //    sv.insertTaoPhieuGiao1(madscl);
    }//GEN-LAST:event_btnTaoPhieuActionPerformed

    private void btnGiaoHanhgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaoHanhgActionPerformed
        // TODO add your handling code here:
        //private int makhcl;
        //    private int madscl;
        for (GioHangDTO gh : GioDTO) {
            pgct1.setMaPhieuGiaoHangChiTiet(madscl);
            pgct1.setMaSanPham(gh.getMaSanPham());
            pgct1.setSoLuong(gh.getSoLuong());
            pgct1.setMaKhachHang(makhcl);
            pgct.add(pgct1);
        }
        for (PhieuGiaoChiTiet ct : pgct) {
            sv.insertTaoPhieuGiao1(ct);
            JOptionPane.showMessageDialog(this, "Giao Hàng");
        }

        //        pghDTO1 = sv.getAllTaoDSPG();
        //        fillTableTaoDSPG(pghDTO1);
        //        JOptionPane.showMessageDialog(this, "Tạo Phiếu Thành Công");
        //    sv.insertTaoPhieuGiao1(madscl);
    }//GEN-LAST:event_btnGiaoHanhgActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        // TODO add your handling code here:

        int selectedRow = tblKhachHang.getSelectedRow();

        if (selectedRow != -1) {
            // Retrieve the value from column 1
            Object valueAtColumn1Object = tblKhachHang.getValueAt(selectedRow, 0);

            // Check if the value is not null and is of type Integer
            if (valueAtColumn1Object != null && valueAtColumn1Object instanceof Integer) {
                int valueAtColumn1 = (int) valueAtColumn1Object;

                // Now you can use 'valueAtColumn1' as needed
                System.out.println("Value at column 1: " + valueAtColumn1);
                setModelkh(khDTO.get(selectedRow));
                // Your existing code...
                makhcl = valueAtColumn1;
                System.out.println("Ma KH " + makhcl);

            } else {
                System.out.println("Value at column 1 is not an Integer or is null.");
            }
        }

        //private int makhcl;
        //    private int madscl;
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void tblKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblKhachHangMouseEntered

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        khDTO = sv.getAlltkKhachHang(txtTimKiemKhachHang.getText());
        fillTableKhachHang(khDTO = sv.getAlltkKhachHang(txtTimKiemKhachHang.getText()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ViewKhachHang().setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblTaoDSPGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTaoDSPGMouseClicked
        //        // TODO add your handling code here:
        int selectedRow = tblTaoDSPG.getSelectedRow();

        if (selectedRow != -1) {
            // Retrieve the value from column 1
            Object valueAtColumn1Object = tblTaoDSPG.getValueAt(selectedRow, 0);

            // Check if the value is not null and is of type Integer
            if (valueAtColumn1Object != null && valueAtColumn1Object instanceof Integer) {
                int valueAtColumn1 = (int) valueAtColumn1Object;

                // Now you can use 'valueAtColumn1' as needed
                System.out.println("Value at column 1: " + valueAtColumn1);
                madscl = valueAtColumn1;
                System.out.println("Ma Hoa Don :" + madscl);
                // Your existing code...
            } else {
                System.out.println("Value at column 1 is not an Integer or is null.");
            }
        }
        //    private int makhcl;
        //    private int madscl;
    }//GEN-LAST:event_tblTaoDSPGMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnGiaoHanhg;
    private javax.swing.JButton btnTaoPhieu;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaKhuyenMai;
    private javax.swing.JComboBox<String> cboTK;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable tblDanhsachsp;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTable tblPhieuGiaoHang1;
    private javax.swing.JTable tblSanPhamDSPG;
    private javax.swing.JTable tblTaoDSPG;
    private javax.swing.JTextArea txtDiaChiGiao;
    private javax.swing.JTextField txtDiaChiTaoPhieu;
    private javax.swing.JTextArea txtGhiChiTaoHoaDon;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JLabel txtGiaoHoanThanh;
    private javax.swing.JLabel txtMaPhieuGiao1;
    private javax.swing.JLabel txtMaSP;
    private javax.swing.JTextField txtMucGiam;
    private javax.swing.JLabel txtNVNhanDon;
    private javax.swing.JTextField txtNguoiNhan;
    private javax.swing.JTextField txtNhanTienKhach;
    private javax.swing.JLabel txtNhanVienGiaoHang;
    private javax.swing.JTextField txtPhiVanChuyen;
    private javax.swing.JLabel txtPhiVanChuyen1;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JLabel txtSoLuong;
    private javax.swing.JLabel txtTenKH;
    private javax.swing.JLabel txtTienKhachDuaDSPG;
    private javax.swing.JTextField txtTimKiemKhachHang;
    private javax.swing.JLabel txtTimeDuKien;
    private javax.swing.JLabel txtTongTien;
    private javax.swing.JLabel txtTongTien15;
    private javax.swing.JLabel txtTongTien16;
    private javax.swing.JLabel txtXacNhanKhachHang;
    // End of variables declaration//GEN-END:variables
   public void fillTableTaoDSPG(List<PhieuGiaoHangDTO1> pghDTO1) {
        DefaultTableModel model2 = (DefaultTableModel) tblTaoDSPG.getModel();
        model2.setRowCount(0);
        for (PhieuGiaoHangDTO1 phieuGiaoHangDTO1 : pghDTO1) {
            Object[] row = new Object[4];
            row[0] = phieuGiaoHangDTO1.getMaPhieuGiaoHang();
            row[1] = phieuGiaoHangDTO1.getTenKhachHang();
            row[2] = phieuGiaoHangDTO1.getMaNhanVien();
            row[3] = phieuGiaoHangDTO1.getTrangThai();
//            mapg = phieuGiaoHangDTO1.getMaPhieuGiaoHang();
            model2.addRow(row);
        }
    }
//    Đang Chuẩn Bị
//    Đã Giao Hàng
//    Đang Vận Chuyển 
//    Thất Lạc Hàng
//    Đang Tạo

    public void fillTableKhachHang(List<KhachHangDTO> khDTO) {
        DefaultTableModel model1 = (DefaultTableModel) tblKhachHang.getModel();
        model1.setRowCount(0);
        for (KhachHangDTO dto : khDTO) {
            Object[] row = new Object[4];
            row[0] = dto.getMaKhachHang();
            row[1] = dto.getHoTen();
            row[2] = dto.getDiaChi();
            row[3] = dto.getDienThoai();
            model1.addRow(row);
        }
        if (model1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Khách hàng không tồn tại !");
            new ViewKhachHang().setVisible(true);

        }
    }
//---------------------------------------------------------------------------------------------------

    public void fillTable(List<PhieuGiaoHang> lpgh1) {

        DefaultTableModel model = (DefaultTableModel) tblPhieuGiaoHang1.getModel();
        model.setRowCount(0);
        for (PhieuGiaoHang pgh : lpgh1) {
            Object[] row = new Object[5];
            row[0] = pgh.getMaPhieuGiao();
            row[1] = pgh.getMaNhanVien();
            row[2] = pgh.getTenKH();
            row[3] = pgh.getGiaoDuKien();
            row[4] = pgh.getTrangThai();

//            row[3] = pgh.getMaNhanVien1();
//            row[4] = pgh.getMaSanPham();
//            row[5] = pgh.getSoLuong();
//            row[6] = pgh.getDiaChiGiaoHang();
//            row[7] = pgh.getGiaoDuKien();
//            row[8] = pgh.getGiaoThucTe() == null ? "Chưa HT" : pgh.getGiaoThucTe();
//            
//            row[10] = (pgh.getKhachHangXacNhan() == 0) ? "Chưa Nhận Hàng" : "Đã Nhận Hàng";
//            row[11] = (pgh.getGhiChu());
//            row[12] = (pgh.getTongTien());
//            row[13] = (pgh.getTienKhachDua());
//            row[14] = (pgh.getPhiVanChuyen());
            model.addRow(row);
        }
    }

    public PhieuGiaoHang getModelpgh() {
        PhieuGiaoHang pgh1 = new PhieuGiaoHang();
        pgh.setMaPhieuGiao(Integer.parseInt(txtMaPhieuGiao1.getText()));
        if (cboTrangThai.getSelectedIndex() == 0) {
            pgh.setTrangThai("Đang Chuẩn Bị");
        } else if (cboTrangThai.getSelectedIndex() == 1) {
            pgh.setTrangThai("Đã Giao Hàng");

        } else if (cboTrangThai.getSelectedIndex() == 2) {
            pgh.setTrangThai("Đang Vận Chuyển");
        } else if (cboTrangThai.getSelectedIndex() == 3) {
            pgh.setTrangThai("Thất Lạc Hàng");
        } else {
            pgh.setTrangThai("Đang Tạo");
        }
        return pgh1;
    }

    public PhieuGiaoHangDTO getModelTaopgh() {
        PhieuGiaoHangDTO pghdto = new PhieuGiaoHangDTO();
        pghdto.setMaKhachHang(makhcl);
        pghdto.setMaNhanVien(1);
        pghdto.setTrangThai("Đang Tạo");
        return pghdto;
    }

    public void setModelpgh(PhieuGiaoHang pgh) {
        txtMaPhieuGiao1.setText(pgh.getMaPhieuGiao() + "");
        mapg1 = pgh.getMaPhieuGiao();
        txtTenKH.setText(pgh.getTenKH());
        txtNVNhanDon.setText(pgh.getMaNhanVien() + "");
        txtNhanVienGiaoHang.setText(pgh.getMaNhanVien1() + "");
        txtMaSP.setText(pgh.getMaSanPham() + "");
        txtTongTien.setText(pgh.getSoLuong() + "");
        txtDiaChiGiao.setText(pgh.getDiaChiGiaoHang());
        txtTimeDuKien.setText(pgh.getGiaoDuKien() + "");
        txtGiaoHoanThanh.setText(pgh.getGiaoThucTe() + "");
        if (pgh.getTrangThai().equals("Đang Chuẩn Bị")) {
            cboTrangThai.setSelectedIndex(0);
        } else if (pgh.getTrangThai().equals("Đã Giao Hàng")) {
            cboTrangThai.setSelectedIndex(1);
        } else if (pgh.getTrangThai().equals("Đang Vận Chuyển")) {
            cboTrangThai.setSelectedIndex(2);
        } else if (pgh.getTrangThai().equals("Thất Lạc Hàng")) {
            cboTrangThai.setSelectedIndex(3);
        } else {
            cboTrangThai.setSelectedIndex(4);
        }
        txtXacNhanKhachHang.setText(pgh.getKhachHangXacNhan() == 1 ? "Đã Nhận Hàng" : "Chưa Nhận Hàng");
        txtGhiChu.setText(pgh.getGhiChu());
        txtTongTien.setText(pgh.getTenKH());
        txtPhiVanChuyen1.setText(pgh.getPhiVanChuyen() + "");
        txtTienKhachDuaDSPG.setText(pgh.getTienKhachDua() + "");
    }

    public void setModelkh(KhachHangDTO khDTO) {
        makh = khDTO.getMaKhachHang();
        txtNguoiNhan.setText(khDTO.getHoTen());
        txtSoDT.setText(khDTO.getDienThoai());
        txtDiaChiTaoPhieu.setText(khDTO.getDiaChi());
    }
//    --------------------------------------------------------------------------------------------------

    public void fillTableSP(List<SanPhamDTO> listSP) {
        DefaultTableModel model1 = (DefaultTableModel) tblDanhsachsp.getModel();
        model1.setRowCount(0);
        for (SanPhamDTO sp : listSP) {
            Object[] row = new Object[7];
            row[0] = sp.getMaSanPham();
//            row[1] = sp.getLoaiSanPham();
            row[1] = sp.getTenSanPham();
            row[2] = sp.getTenLoai();
//            row[5] = sp.getSoLuong();
            row[3] = sp.getSize();
            row[4] = sp.getTrangThai();
            row[5] = sp.getGia();
            row[6] = sp.getMoTa();
            model1.addRow(row);
        }
    }

    public void fillSanPhamDSPG(List<PhieuGiaoChiTiet> pgct) {
        DefaultTableModel model2 = (DefaultTableModel) tblSanPhamDSPG.getModel();
        model2.setRowCount(0);
        for (PhieuGiaoChiTiet dto : pgct) {
            Object[] row = new Object[4];
            row[0] = dto.getMaPhieuGiaoHangChiTiet();
            row[1] = dto.getMaSanPham();
            row[2] = dto.getSoLuong();
            row[3] = dto.getMaKhachHang();
            model2.addRow(row);
        }
    }

    public void fillGioHang(List<GioHangDTO> GioDTO) {
        DefaultTableModel model2 = (DefaultTableModel) tblGioHang.getModel();
        model2.setRowCount(0);
        for (GioHangDTO dto : GioDTO) {
            Object[] row = new Object[8];
            row[0] = dto.getMaSanPham();
//            row[1] = sp.getLoaiSanPham();
            row[1] = dto.getTenSanPham();
            row[2] = dto.getTenLoai();
//            row[5] = sp.getSoLuong();
            row[3] = dto.getSize();
            row[4] = dto.getTrangThai();
            row[5] = dto.getGia();
            row[6] = dto.getMoTa();
            row[7] = dto.getSoLuong();
            model2.addRow(row);
        }
    }
//    public void fillTableGioHang(List<GioHangDTO> GioDTO) {
//        DefaultTableModel model1 = (DefaultTableModel) tblDanhsachsp.getModel();
////        tblModel.setRowCount(0);
//        for (SanPham sp : listSP) {
//            Object[] row = new Object[7];
//            row[0] = sp.getMaSanPham();
//            row[1] = sp.getLoaiSanPham();
//            row[2] = sp.getTenSanPham();
//            row[3] = sp.getMoTa();
//            row[4] = sp.getGia();
//            row[5] = sp.getSoLuong();
//            row[6] = sp.getImages();
//            model1.addRow(row);
//        }
//    }

    //--------------------------------------------------------------------------------------------------------
    public void initCBOKhuyenMai() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMaKhuyenMai.getModel();
        model.removeAllElements();
        listdto = sv.getAllcboPhieuGiam();
        for (DotGiamGiaDTO dto : listdto) {
            model.addElement(dto.getTenDotGiamGia());
//            if(dto.getTenDotGiamGia()==cboMaKhuyenMai.getSelectedItem()){
//                txtMucGiam2.setText(dto.getPhanTramGiam()+"%");
//            }
        }
        cboMaKhuyenMai.setSelectedIndex(0);
    }

    public void checkMucGiamGia(String ma) {
        // Assuming listdto is already initialized somewhere in your code

        for (DotGiamGiaDTO dto : listdto) {
            // Use equals method for string comparison
            if (dto.getTenDotGiamGia().equals(ma)) {
                txtMucGiam.setText(dto.getPhanTramGiam() + "%");
                break; // Assuming you want to exit the loop once a match is found
            }
        }
    }

    public PhieuGiaoChiTiet GiaoHang() {
        PhieuGiaoChiTiet pgct = new PhieuGiaoChiTiet();

        for (GioHangDTO dto : GioDTO) {
            pgct.setMaPhieuGiaoHangChiTiet(mapg);
            pgct.setMaSanPham(dto.getMaSanPham());
            pgct.setSoLuong(dto.getSoLuong());
            pgct.setMaKhachHang(makh);

        }
        return pgct;
    }

    public PhieuGiaoHang GiaoHang1() {
        PhieuGiaoHang lpgh1 = new PhieuGiaoHang();

        lpgh1.setMaPhieuGiao(mapg);
        lpgh1.setgetMaNhanVien1(6);
        lpgh1.setDiaChiGiaoHang(txtDiaChiTaoPhieu.getText());
        lpgh1.setTrangThai("Đang Vận Chuyển ");
        lpgh1.setGhiChu(txtGhiChiTaoHoaDon.getText());
        // Assuming lpgh1 has a property of type BigDecimal
        BigDecimal tienKhachDua = new BigDecimal(txtNhanTienKhach.getText());
        lpgh1.setTienKhachDua(tienKhachDua);
        BigDecimal PhiVanChuyen = new BigDecimal(txtPhiVanChuyen.getText());
        lpgh1.setPhiVanChuyen(PhiVanChuyen);
        BigDecimal tongtien = new BigDecimal(txtTongTien16.getText());
        lpgh1.setTongTien(tongtien);

        return lpgh1;
    }
}
